# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Transformer Models Explained
author: Ricardo Coronado
copyright: "2023"
logo: logo.png
only_build_toc_files: true


execute:
  execute_notebooks: force
  allow_errors: true

repository:
  url: https://github.com/recmera/transformer-models-explained  # Online location of your book

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: false
  only_build_toc_files: true

sphinx:
  config:
    html_show_copyright: false
    language: es
    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
latex:
  latex_documents:
    targetname: book.tex